# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

env:
  MAVEN_VERSION: 3.6.3
  SHA: c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0
  BASE_URL: https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries

on:
  workflow_dispatch:
    branches:
      - master
  release:
    types: [created]
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Install Maven
      env:
        MAVEN_VERSION: 3.6.3
        SHA: c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0
        BASE_URL: https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries 
      run: |
        mkdir -p /usr/share/maven /usr/share/maven/ref
        curl -fsSL -o /tmp/apache-maven.tar.gz ${{ env.BASE_URL }}/apache-maven-${{ ebv.MAVEN_VERSION }}-bin.tar.gz
        echo "${{ env.SHA }} /tmp/apache-maven.tar.gz" | sha512sum -c -
        tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1
        rm -f /tmp/apache-maven.tar.gz
        ln -s /usr/share/maven/bin/mvn /usr/bin/mvn
        mvn --version

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
